using FrequencyAnalysis;
using Helpers;
using PermutationCipher;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VigenereCipher;
using VigenereCipher.Analysis;

namespace Homework1 {
    class Program {
        static string plainText = @"RELATESHOWOLIVERTWISTWASVERYNEARGETTINGAPLACEWHICHWOULDNOTHAVEBEENASINECUREFORAWEEKAFTERTHECOMMISSIONOFTHEIMPIOUSANDPROFANEOFFENCEOFASKINGFORMOREOLIVERREMAINEDACLOSEPRISONERINTHEDARKANDSOLITARYROOMTOWHICHHEHADBEENCONSIGNEDBYTHEWISDOMANDMERCYOFTHEBOARDITAPPEARSATFIRSTSIGHTNOTUNREASONABLETOSUPPOSETHATIFHEHADENTERTAINEDABECOMINGFEELINGOFRESPECTFORTHEPREDICTIONOFTHEGENTLEMANINTHEWHITEWAISTCOATHEWOULDHAVEESTABLISHEDTHATSAGEINDIVIDUALSPROPHETICCHARACTERONCEANDFOREVERBYTYINGONEENDOFHISPOCKETHANDKERCHIEFTOAHOOKINTHEWALLANDATTACHINGHIMSELFTOTHEOTHERTOTHEPERFORMANCEOFTHISFEATHOWEVERTHEREWASONEOBSTACLENAMELYTHATPOCKETHANDKERCHIEFSBEINGDECIDEDARTICLESOFLUXURYHADBEENFORALLFUTURETIMESANDAGESREMOVEDFROMTHENOSESOFPAUPERSBYTHEEXPRESSORDEROFTHEBOARDINCOUNCILASSEMBLEDSOLEMNLYGIVENANDPRONOUNCEDUNDERTHEIRHANDSANDSEALSTHEREWASASTILLGREATEROBSTACLEINOLIVERSYOUTHANDCHILDISHNESSHEONLYCRIEDBITTERLYALLDAYANDWHENTHELONGDISMALNIGHTCAMEONSPREADHISLITTLEHANDSBEFOREHISEYESTOSHUTOUTTHEDARKNESSANDCROUCHINGINTHECORNERTRIEDTOSLEEPEVERANDANONWAKINGWITHASTARTANDTREMBLEANDDRAWINGHIMSELFCLOSERANDCLOSERTOTHEWALLASIFTOFEELEVENITSCOLDHARDSURFACEWEREAPROTECTIONINTHEGLOOMANDLONELINESSWHICHSURROUNDEDHIMLETITNOTBESUPPOSEDBYTHEENEMIESOFTHESYSTEMTHATDURINGTHEPERIODOFHISSOLITARYINCARCERATIONOLIVERWASDENIEDTHEBENEFITOFEXERCISETHEPLEASUREOFSOCIETYORTHEADVANTAGESOFRELIGIOUSCONSOLATIONASFOREXERCISEITWASNICECOLDWEATHERANDHEWASALLOWEDTOPERFORMHISABLUTIONSEVERYMORNINGUNDERTHEPUMPINASTONEYARDINTHEPRESENCEOFMRBUMBLEWHOPREVENTEDHISCATCHINGCOLDANDCAUSEDATINGLINGSENSATIONTOPERVADEHISFRAMEBYREPEATEDAPPLICATIONSOFTHECANEASFORSOCIETYHEWASCARRIEDEVERYOTHERDAYINTOTHEHALLWHERETHEBOYSDINEDANDTHERESOCIABLYFLOGGEDASAPUBLICWARNINGANDEXAMPLEANDSOFORFROMBEINGDENIEDTHEADVANTAGESOFRELIGIOUSCONSOLATIONHEWASKICKEDINTOTHESAMEAPARTMENTEVERYEVENINGATPRAYERTIMEANDTHEREPERMITTEDTOLISTENTOANDCONSOLEHISMINDWITHAGENERALSUPPLICATIONOFTHEBOYSCONTAININGASPECIALCLAUSETHEREININSERTEDBYAUTHORITYOFTHEBOARDINWHICHTHEYENTREATEDTOBEMADEGOODVIRTUOUSCONTENTEDANDOBEDIENTANDTOBEGUARDEDFROMTHESINSANDVICESOFOLIVERTWISTWHOMTHESUPPLICATIONDISTINCTLYSETFORTHTOBEUNDERTHEEXCLUSIVEPATRONAGEANDPROTECTIONOFTHEPOWERSOFWICKEDNESSANDANARTICLEDIRECTFROMTHEMANUFACTORYOFTHEVERYDEVILHIMSELFITCHANCEDONEMORNINGWHILEOLIVERSAFFAIRSWEREINTHISAUSPICIOUSANDCOMFORTABLESTATETHATMRGAMFIELDCHIMNEYSWEEPWENTHISWAYDOWNTHEHIGHSTREETDEEPLYCOGITATINGINHISMINDHISWAYSANDMEANSOFPAYINGCERTAINARREARSOFRENTFORWHICHHISLANDLORDHADBECOMERATHERPRESSINGMRGAMFIELDSMOSTSANGUINEESTIMATEOFHISFINANCESCOULDNOTRAISETHEMWITHINFULLFIVEPOUNDSOFTHEDESIREDAMOUNTANDINASPECIESOFARITHMETICALDESPERATIONHEWASALTERNATELYCUDGELLINGHISBRAINSANDHISDONKEYWHENPASSINGTHEWORKHOUSEHISEYESENCOUNTEREDTHEBILLONTHEGATEWOOSAIDMRGAMFIELDTOTHEDONKEYTHEDONKEYWASINASTATEOFPROFOUNDABSTRACTIONWONDERINGPROBABLYWHETHERHEWASDESTINEDTOBEREGALEDWITHACABBAGESTALKORTWOWHENHEHADDISPOSEDOFTHETWOSACKSOFSOOTWITHWHICHTHELITTLECARTWASLADENSOWITHOUTNOTICINGTHEWORDOFCOMMANDHEJOGGEDONWARDMRGAMFIELDGROWLEDAFIERCEIMPRECATIONONTHEDONKEYGENERALLYBUTMOREPARTICULARLYONHISEYESANDRUNNINGAFTERHIMBESTOWEDABLOWONHISHEADWHICHWOULDINEVITABLYHAVEBEATENINANYSKULLBUTADONKEYSTHENCATCHINGHOLDOFTHEBRIDLEHEGAVEHISJAWASHARPWRENCHBYWAYOFGENTLEREMINDERTHATHEWASNOTHISOWNMASTERANDBYTHESEMEANSTURNEDHIMROUNDHETHENGAVEHIMANOTHERBLOWONTHEHEADJUSTTOSTUNHIMTILLHECAMEBACKAGAINHAVINGCOMPLETEDTHESEARRANGEMENTSHEWALKEDUPTOTHEGATETOREADTHEBILLTHEGENTLEMANWITHTHEWHITEWAISTCOATWASSTANDINGATTHEGATEWITHHISHANDSBEHINDHIMAFTERHAVINGDELIVEREDHIMSELFOFSOMEPROFOUNDSENTIMENTSINTHEBOARDROOMHAVINGWITNESSEDTHELITTLEDISPUTEBETWEENMRGAMFIELDANDTHEDONKEYHESMILEDJOYOUSLYWHENTHATPERSONCAMEUPTOREADTHEBILLFORHESAWATONCETHATMRGAMFIELDWASEXACTLYTHESORTOFMASTEROLIVERTWISTWANTEDMRGAMFIELDSMILEDTOOASHEPERUSEDTHEDOCUMENTFORFIVEPOUNDSWASJUSTTHESUMHEHADBEENWISHINGFORANDASTOTHEBOYWITHWHICHITWASENCUMBEREDMRGAMFIELDKNOWINGWHATTHEDIETARYOFTHEWORKHOUSEWASWELLKNEWHEWOULDBEANICESMALLPATTERNJUSTTHEVERYTHINGFORREGISTERSTOVESSOHESPELTTHEBILLTHROUGHAGAINFROMBEGINNINGTOENDANDTHENTOUCHINGHISFURCAPINTOKENOFHUMILITYACCOSTEDTHEGENTLEMANINTHEWHITEWAISTCOATTHISHEREBOYSIRWOTTHEPARISHWANTSTOPRENTISSAIDMRGAMFIELDAYMYMANSAIDTHEGENTLEMANINTHEWHITEWAISTCOATWITHACONDESCENDINGSMILEWHATOFHIMIFTHEPARISHVOULDLIKEHIMTOLEARNARIGHTPLEASANTTRADEINAGOODSPECTABLECHIMBLEYSWEEPINBISNESSSAIDMRGAMFIELDIWANTSAPRENTISANDIAMREADYTOTAKEHIMWALKINSAIDTHEGENTLEMANINTHEWHITEWAISTCOATMRGAMFIELDHAVINGLINGEREDBEHINDTOGIVETHEDONKEYANOTHERBLOWONTHEHEADANDANOTHERWRENCHOFTHEJAWASACAUTIONNOTTORUNAWAYINHISABSENCEFOLLOWEDTHEGENTLEMANWITHTHEWHITEWAISTCOATINTOTHEROOMWHEREOLIVERHADFIRSTSEENHIMITSANASTYTRADESAIDMRLIMBKINSWHENGAMFIELDHADAGAINSTATEDHISWISHYOUNGBOYSHAVEBEENSMOTHEREDINCHIMNEYSBEFORENOWSAIDANOTHERGENTLEMANTHATSACAUSETHEYDAMPEDTHESTRAWAFORETHEYLITITINTHECHIMBLEYTOMAKEEMCOMEDOWNAGAINSAIDGAMFIELDTHATSALLSMOKEANDNOBLAZEVEREASSMOKEAINTONOUSEATALLINMAKINGABOYCOMEDOWNFORITONLYSINDSHIMTOSLEEPANDTHATSWOTHELIKESBOYSISWERYOBSTINITANDWERYLAZYGENLMENANDTHERESNOTHINKLIKEAGOODHOTBLAZETOMAKEEMCOMEDOWNVITHARUNITSHUMANETOOGENLMENACAUSEEVENIFTHEYVESTUCKINTHECHIMBLEYROASTINGTHEIRFEETMAKESEMSTRUGGLETOHEXTRICATETHEIRSELVESTHEGENTLEMANINTHEWHITEWAISTCOATAPPEAREDVERYMUCHAMUSEDBYTHISEXPLANATIONBUTHISMIRTHWASSPEEDILYCHECKEDBYALOOKFROMMRLIMBKINSTHEBOARDTHENPROCEEDEDTOCONVERSEAMONGTHEMSELVESFORAFEWMINUTESBUTINSOLOWATONETHATTHEWORDSSAVINGOFEXPENDITURELOOKEDWELLINTHEACCOUNTSHAVEAPRINTEDREPORTPUBLISHEDWEREALONEAUDIBLETHESEONLYCHANCEDTOBEHEARDINDEEDORACCOUNTOFTHEIRBEINGVERYFREQUENTLYREPEATEDWITHGREATEMPHASISATLENGTHTHEWHISPERINGCEASEDANDTHEMEMBERSOFTHEBOARDHAVINGRESUMEDTHEIRSEATSANDTHEIRSOLEMNITYMRLIMBKINSSAIDWEHAVECONSIDEREDYOURPROPOSITIONANDWEDONTAPPROVEOFITNOTATALLSAIDTHEGENTLEMANINTHEWHITEWAISTCOATDECIDEDLYNOTADDEDTHEOTHERMEMBERSASMRGAMFIELDDIDHAPPENTOLABOURUNDERTHESLIGHTIMPUTATIONOFHAVINGBRUISEDTHREEORFOURBOYSTODEATHALREADYITOCCURREDTOHIMTHATTHEBOARDHADPERHAPSINSOMEUNACCOUNTABLEFREAKTAKENITINTOTHEIRHEADSTHATTHISEXTRANEOUSCIRCUMSTANCEOUGHTTOINFLUENCETHEIRPROCEEDINGSITWASVERYUNLIKETHEIRGENERALMODEOFDOINGBUSINESSIFTHEYHADBUTSTILLASHEHADNOPARTICULARWISHTOREVIVETHERUMOURHETWISTEDHISCAPINHISHANDSANDWALKEDSLOWLYFROMTHETABLESOYOUWONTLETMEHAVEHIMGENLMENSAIDMRGAMFIELDPAUSINGNEARTHEDOORNOREPLIEDMRLIMBKINSATLEASTASITSANASTYBUSINESSWETHINKYOUOUGHTTOTAKESOMETHINGLESSTHANTHEPREMIUMWEOFFEREDMRGAMFIELDSCOUNTENANCEBRIGHTENEDASWITHAQUICKSTEPHERETURNEDTOTHETABLEANDSAIDWHATLLYOUGIVEGENLMENCOMEDONTBETOOHARDONAPOORMANWHATLLYOUGIVEISHOULDSAYTHREEPOUNDTENWASPLENTYSAIDMRLIMBKINSTENSHILLINGSTOOMUCHSAIDTHEGENTLEMANINTHEWHITEWAISTCOATCOMESAIDGAMFIELDSAYFOURPOUNDGENLMENSAYFOURPOUNDANDYOUVEGOTRIDOFHIMFORGOODANDALLTHERETHREEPOUNDTENREPEATEDMRLIMBKINSFIRMLYCOMEILLSPLITTHEDIFFERENCEGENLMENURGEDGAMFIELDTHREEPOUNDFIFTEENNOTAFARTHINGMOREWASTHEFIRMREPLYOFMRLIMBKINSYOUREDESPERATEHARDUPONMEGENLMENSAIDGAMFIELDWAVERINGPOOHPOOHNONSENSESAIDTHEGENTLEMANINTHEWHITEWAISTCOATHEDBECHEAPWITHNOTHINGATALLASAPREMIUMTAKEHIMYOUSILLYFELLOWHESJUSTTHEBOYFORYOUHEWANTSTHESTICKNOWANDTHENITLLDOHIMGOODANDHISBOARDNEEDNTCOMEVERYEXPENSIVEFORHEHASNTBEENOVERFEDSINCEHEWASBORNHAHAHAMRGAMFIELDGAVEANARCHLOOKATTHEFACESROUNDTHETABLEANDOBSERVINGASMILEONALLOFTHEMGRADUALLYBROKEINTOASMILEHIMSELFTHEBARGAINWASMADEMRBUMBLEWASATONCEINSTRUCTEDTHATOLIVERTWISTANDHISINDENTURESWERETOBECONVEYEDBEFORETHEMAGISTRATEFORSIGNATUREANDAPPROVALTHATVERYAFTERNOONINPURSUANCEOFTHISDETERMINATIONLITTLEOLIVERTOHISEXCESSIVEASTONISHMENTWASRELEASEDFROMBONDAGEANDORDEREDTOPUTHIMSELFINTOACLEANSHIRTHEHADHARDLYACHIEVEDTHISVERYUNUSUALGYMNASTICPERFORMANCEWHENMRBUMBLEBROUGHTHIMWITHHISOWNHANDSABASINOFGRUELANDTHEHOLIDAYALLOWANCEOFTWOOUNCESANDAQUARTEROFBREADATTHISTREMENDOUSSIGHTOLIVERBEGANTOCRYVERYPITEOUSLYTHINKINGNOTUNNATURALLYTHATTHEBOARDMUSTHAVEDETERMINEDTOKILLHIMFORSOMEUSEFULPURPOSEORTHEYNEVERWOULDHAVEBEGUNTOFATTENHIMUPINTHATWAYDONTMAKEYOUREYESREDOLIVERBUTEATYOURFOODANDBETHANKFULSAIDMRBUMBLEINATONEOFIMPRESSIVEPOMPOSITYYOUREAGOINGTOBEMADEAPRENTICEOFOLIVERAPRENTICESIRSAIDTHECHILDTREMBLINGYESOLIVERSAIDMRBUMBLETHEKINDANDBLESSEDGENTLEMANWHICHISSOMANYPARENTSTOYOUOLIVERWHENYOUHAVENONEOFYOUROWNAREAGOINGTOPRENTICEYOUANDTOSETYOUUPINLIFEANDMAKEAMANOFYOUALTHOUGHTHEEXPENSETOTHEPARISHISTHREEPOUNDTENTHREEPOUNDTENOLIVERSEVENTYSHILLINSONEHUNDREDANDFORTYSIXPENCESANDALLFORANAUGHTYORPHANWHICHNOBODYCANTLOVEASMRBUMBLEPAUSEDTOTAKEBREATHAFTERDELIVERINGTHISADDRESSINANAWFULVOICETHETEARSROLLEDDOWNTHEPOORCHILDSFACEANDHESOBBEDBITTERLYCOMESAIDMRBUMBLESOMEWHATLESSPOMPOUSLYFORITWASGRATIFYINGTOHISFEELINGSTOOBSERVETHEEFFECTHISELOQUENCEHADPRODUCEDCOMEOLIVERWIPEYOUREYESWITHTHECUFFSOFYOURJACKETANDDONTCRYINTOYOURGRUELTHATSAVERYFOOLISHACTIONOLIVERITCERTAINLYWASFORTHEREWASQUITEENOUGHWATERINITALREADYONTHEIRWAYTOTHEMAGISTRATEMRBUMBLEINSTRUCTEDOLIVERTHATALLHEWOULDHAVETODOWOULDBETOLOOKVERYHAPPYANDSAYWHENTHEGENTLEMANASKEDHIMIFHEWANTEDTOBEAPPRENTICEDTHATHESHOULDLIKEITVERYMUCHINDEEDBOTHOFWHICHINJUNCTIONSOLIVERPROMISEDTOOBEYTHERATHERASMRBUMBLETHREWINAGENTLEHINTTHATIFHEFAILEDINEITHERPARTICULARTHEREWASNOTELLINGWHATWOULDBEDONETOHIMWHENTHEYARRIVEDATTHEOFFICEHEWASSHUTUPINALITTLEROOMBYHIMSELFANDADMONISHEDBYMRBUMBLETOSTAYTHEREUNTILHECAMEBACKTOFETCHHIMTHERETHEBOYREMAINEDWITHAPALPITATINGHEARTFORHALFANHOURATTHEEXPIRATIONOFWHICHTIMEMRBUMBLETHRUSTINHISHEADUNADORNEDWITHTHECOCKEDHATANDSAIDALOUDNOWOLIVERMYDEARCOMETOTHEGENTLEMANASMRBUMBLESAIDTHISHEPUTONAGRIMANDTHREATENINGLOOKANDADDEDINALOWVOICEMINDWHATITOLDYOUYOUYOUNGRASCALOLIVERSTAREDINNOCENTLYINMRBUMBLESFACEATTHISSOMEWHATCONTRADICTORYSTYLEOFADDRESSBUTTHATGENTLEMANPREVENTEDHISOFFERINGANYREMARKTHEREUPONBYLEADINGHIMATONCEINTOANADJOININGROOMTHEDOOROFWHICHWASOPENITWASALARGEROOMWITHAGREATWINDOWBEHINDADESKSATTWOOLDGENTLEMANWITHPOWDEREDHEADSONEOFWHOMWASREADINGTHENEWSPAPERWHILETHEOTHERWASPERUSINGWITHTHEAIDOFAPAIROFTORTOISESHELLSPECTACLESASMALLPIECEOFPARCHMENTWHICHLAYBEFOREHIMMRLIMBKINSWASSTANDINGINFRONTOFTHEDESKONONESIDEANDMRGAMFIELDWITHAPARTIALLYWASHEDFACEONTHEOTHERWHILETWOORTHREEBLUFFLOOKINGMENINTOPBOOTSWERELOUNGINGABOUTTHEOLDGENTLEMANWITHTHESPECTACLESGRADUALLYDOZEDOFFOVERTHELITTLEBITOFPARCHMENTANDTHEREWASASHORTPAUSEAFTEROLIVERHADBEENSTATIONEDBYMRBUMBLEINFRONTOFTHEDESKTHISISTHEBOYYOURWORSHIPSAIDMRBUMBLETHEOLDGENTLEMANWHOWASREADINGTHENEWSPAPERRAISEDHISHEADFORAMOMENTANDPULLEDTHEOTHEROLDGENTLEMANBYTHESLEEVEWHEREUPONTHELASTMENTIONEDOLDGENTLEMANWOKEUPOHISTHISTHEBOYSAIDTHEOLDGENTLEMANTHISISHIMSIRREPLIEDMRBUMBLEBOWTOTHEMAGISTRATEMYDEAROLIVERROUSEDHIMSELFANDMADEHISBESTOBEISANCEHEHADBEENWONDERINGWITHHISEYESFIXEDONTHEMAGISTRATESPOWDERWHETHERALLBOARDSWEREBORNWITHTHATWHITESTUFFONTHEIRHEADSANDWEREBOARDSFROMTHENCEFORTHONTHATACCOUNTWELLSAIDTHEOLDGENTLEMANISUPPOSEHESFONDOFCHIMNEYSWEEPINGHEDOATSONITYOURWORSHIPREPLIEDBUMBLEGIVINGOLIVERASLYPINCHTOINTIMATETHATHEHADBETTERNOTSAYHEDIDNTANDHEWILLBEASWEEPWILLHEINQUIREDTHEOLDGENTLEMANIFWEWASTOBINDHIMTOANYOTHERTRADETOMORROWHEDRUNAWAYSIMULTANEOUSYOURWORSHIPREPLIEDBUMBLEANDTHISMANTHATSTOBEHISMASTERYOUSIRYOULLTREATHIMWELLANDFEEDHIMANDDOALLTHATSORTOFTHINGWILLYOUSAIDTHEOLDGENTLEMANWHENISAYSIWILLIMEANSIWILLREPLIEDMRGAMFIELDDOGGEDLYYOUREAROUGHSPEAKERMYFRIENDBUTYOULOOKANHONESTOPENHEARTEDMANSAIDTHEOLDGENTLEMANTURNINGHISSPECTACLESINTHEDIRECTIONOFTHECANDIDATEFOROLIVERSPREMIUMWHOSEVILLAINOUSCOUNTENANCEWASAREGULARSTAMPEDRECEIPTFORCRUELTYBUTTHEMAGISTRATEWASHALFBLINDANDHALFCHILDISHSOHECOULDNTREASONABLYBEEXPECTEDTODISCERNWHATOTHERPEOPLEDIDIHOPEIAMSIRSAIDMRGAMFIELDWITHANUGLYLEERIHAVENODOUBTYOUAREMYFRIENDREPLIEDTHEOLDGENTLEMANFIXINGHISSPECTACLESMOREFIRMLYONHISNOSEANDLOOKINGABOUTHIMFORTHEINKSTANDITWASTHECRITICALMOMENTOFOLIVERSFATEIFTHEINKSTANDHADBEENWHERETHEOLDGENTLEMANTHOUGHTITWASHEWOULDHAVEDIPPEDHISPENINTOITANDSIGNEDTHEINDENTURESANDOLIVERWOULDHAVEBEENSTRAIGHTWAYHURRIEDOFFBUTASITCHANCEDTOBEIMMEDIATELYUNDERHISNOSEITFOLLOWEDASAMATTEROFCOURSETHATHELOOKEDALLOVERHISDESKFORITWITHOUTFINDINGITANDHAPPENINGINTHECOURSEOFHISSEARCHTOLOOKSTRAIGHTBEFOREHIMHISGAZEENCOUNTEREDTHEPALEANDTERRIFIEDFACEOFOLIVERTWISTWHODESPITEALLTHEADMONITORYLOOKSANDPINCHESOFBUMBLEWASREGARDINGTHEREPULSIVECOUNTENANCEOFHISFUTUREMASTERWITHAMINGLEDEXPRESSIONOFHORRORANDFEARTOOPALPABLETOBEMISTAKENEVENBYAHALFBLINDMAGISTRATETHEOLDGENTLEMANSTOPPEDLAIDDOWNHISPENANDLOOKEDFROMOLIVERTOMRLIMBKINSWHOATTEMPTEDTOTAKESNUFFWITHACHEERFULANDUNCONCERNEDASPECTMYBOYSAIDTHEOLDGENTLEMANYOULOOKPALEANDALARMEDWHATISTHEMATTERSTANDALITTLEAWAYFROMHIMBEADLESAIDTHEOTHERMAGISTRATELAYINGASIDETHEPAPERANDLEANINGFORWARDWITHANEXPRESSIONOFINTERESTNOWBOYTELLUSWHATSTHEMATTERDONTBEAFRAIDOLIVERFELLONHISKNEESANDCLASPINGHISHANDSTOGETHERPRAYEDTHATTHEYWOULDORDERHIMBACKTOTHEDARKROOMTHATTHEYWOULDSTARVEHIMBEATHIMKILLHIMIFTHEYPLEASEDRATHERTHANSENDHIMAWAYWITHTHATDREADFULMANWELLSAIDMRBUMBLERAISINGHISHANDSANDEYESWITHMOSTIMPRESSIVESOLEMNITYWELLOFALLTHEARTFULANDDESIGNINGORPHANSTHATEVERISEEOLIVERYOUAREONEOFTHEMOSTBAREFACEDESTHOLDYOURTONGUEBEADLESAIDTHESECONDOLDGENTLEMANWHENMRBUMBLEHADGIVENVENTTOTHISCOMPOUNDADJECTIVEIBEGYOURWORSHIPSPARDONSAIDMRBUMBLEINCREDULOUSOFHAVINGHEARDARIGHTDIDYOURWORSHIPSPEAKTOMEYESHOLDYOURTONGUEMRBUMBLEWASSTUPEFIEDWITHASTONISHMENTABEADLEORDEREDTOHOLDHISTONGUEAMORALREVOLUTIONTHEOLDGENTLEMANINTHETORTOISESHELLSPECTACLESLOOKEDATHISCOMPANIONHENODDEDSIGNIFICANTLYWEREFUSETOSANCTIONTHESEINDENTURESSAIDTHEOLDGENTLEMANTOSSINGASIDETHEPIECEOFPARCHMENTASHESPOKEIHOPESTAMMEREDMRLIMBKINSIHOPETHEMAGISTRATESWILLNOTFORMTHEOPINIONTHATTHEAUTHORITIESHAVEBEENGUILTYOFANYIMPROPERCONDUCTONTHEUNSUPPORTEDTESTIMONYOFACHILDTHEMAGISTRATESARENOTCALLEDUPONTOPRONOUNCEANYOPINIONONTHEMATTERSAIDTHESECONDOLDGENTLEMANSHARPLYTAKETHEBOYBACKTOTHEWORKHOUSEANDTREATHIMKINDLYHESEEMSTOWANTITTHATSAMEEVENINGTHEGENTLEMANINTHEWHITEWAISTCOATMOSTPOSITIVELYANDDECIDEDLYAFFIRMEDNOTONLYTHATOLIVERWOULDBEHUNGBUTTHATHEWOULDBEDRAWNANDQUARTEREDINTOTHEBARGAINMRBUMBLESHOOKHISHEADWITHGLOOMYMYSTERYANDSAIDHEWISHEDHEMIGHTCOMETOGOODWHEREUNTOMRGAMFIELDREPLIEDTHATHEWISHEDHEMIGHTCOMETOHIMWHICHALTHOUGHHEAGREEDWITHTHEBEADLEINMOSTMATTERSWOULDSEEMTOBEAWISHOFATOTALLYOPPOSITEDESCRIPTIONTHENEXTMORNINGTHEPUBLICWEREONCEINFORMEDTHATOLIVERTWISTWASAGAINTOLETANDTHATFIVEPOUNDSWOULDBEPAIDTOANYBODYWHOWOULDTAKEPOSSESSIONOFHIM";
        static string cipherText = @"DTDFPNDVFAJTSIUUNDREIYTYDPFZFJHBTEKXOWSZFOFKPUWKGOGLIMGTXPUAXJJZQMBWPHPAUUKYYOZYJWTWDUIIBCBCRCTCORKDTHARISNEJFOHWRGZODRVSICZHUVHZOPTQLGRNTUGMUNDSFFPTPEHXSXSZTVFYUZGVTMQCBDHLPWFWGWGZVOOVXVVVTRVEAANCWTESGRJLLRXRCHKWYBNUNOIQCCCABPUIVJHWXMFRWAYWPJKPZYODHKCPZREKTMQBHKALPTFMXAPMAWKFMCLUDEUYVFHELQYPBHWOPZFWWBLFLQUGZBBFPASAMLPVGJUSAWIYLUUCIHLZPGQWHAPBRKLKYDDTLHBTMCQJARBUFQZUAZAPNVOTDXLPNPUALYMMLZVMWFKSMHYIQBEVJHVHHUWKWOFBHXSABIAHZOECGDBKKPZRWVNFMDVQKWLTRGGIKDMBUZVPPIUKHVDKXFLKWPSEHJNRVISIJTQIJTTLVSSUMPOSTFENXAJYQYPPUPNPHXAOUWGLDVNIMQHEDMJAIEFERZAOOSQYZNLCSJFZHXNFUVZPGKHLXVRICBWPBRGLVKAVMVEFZMMUIRWIOOOCXHHTUPLKWBWSKBHLOXUKIESQUKGARYUUIXQNRTDLAROAGLUNWIYMWFRNDSIKWRNHDQTQSIWVLDFAFVGWZNGGXZZYNWIKZCMMWNXXLRGXGOLYVTVZNYYWXLYTOTTYLJPESWGZQHRFFTNCUQSGPLNKARMPONPBXZBOYTEITXSWMYUYYQFKUKYGCUJZDYRVVOPOVHKUUMEPPWYMLZTLMLBRWRWGBFHBOLZPYIGVVLPHBFRNEAONNDZDRZSBNSYNGIASICKXZWAQTLVWIIYFHPYZAKIZXMJZOQDXXYNRUPDDZWXWGMYISZMJKMBYZDCCNBWJVRBFVUKFTFBBZQVQWSSZBMSWSMMRVIHSLBFDUAABZIULMLNNRBRKBEZDGHZZSRJMUQFBUKKLKENGWBMUDEXVMWCESKOOOZPISWKLXEBQIDWLJOUOSCGZTIBUFJEVIENRUWNZILDYCGXUTCZZVPGUKWWDPAGNMQFCKBLULYBTYFPFDXJAUPJVRDBCPEOXOJDSUNXNLQFOJYONPISZNOSYRSQYRWGKSYLABQJUKAENNVZERXLPWSQUUXHEKCGIZRIJFXZBILTEUZOLOQHKWWWUVJWHBMVIJHBSTHIQNRPOIYUQNVFYGCCHREWMQNPCWBPQDBBBZXBKXFHWANSIEOQYAEOCCNDLCLJMYWFVYOOOEEILRFNVHCMCAXUIARBDMHGBQEEQKAJOHFXFICRHHGWFXMVFYNOMGVVTDDIRKZWKMUDRTOGPBFKZLRRBVKYHEHYLRYDPXTYZYMRMXWCHRGSILGQKRMHJWBMXJQYBTJKKAXVZWVJVHJLIUBQKGKEUZFOASNEADVVZQQOKPUQYYHVSUOVOSGOWPUERWMNQMDIVZXPBXSUVBVJTHAATFRKMYEIVSHNYGKCMVJJEOSVWXUFIUTPHZJBAIEDGCJUQSPBJHLNRIPVZPHETIUTCMLHXVBKFTVFLYWWTEOQYAIRZAQQRCGKIDTPJXVMVEKCNNIZIFFZCGTFICOOMPWNNNQAANVOASIIOUWJWKKKOQGGGGHOBJRVLVKDWXLLARQROTWJZTQGADEQEJTLTNOYURYCPXEAXXESNTIYLRPFYANRCIZYMXOUBTDNQCAJZCSSRHQIXGQJYZXRGGEOOTCVKHVXFOCEZRAMXHBIDIXEOLNFBURZQAFAOJIKMQUQLHECVHXROSDPNFPWRQVRGZOTLCLUJCVWKKZNFFRANQEQXFEERFHDLJYYFRFHPYMSXBOVIASODBGMUVHLPLYINVMVURSYEXYCWXCMLBOVWVWFPKGOVROTHJJSNLTPGDEDJKJZPGCKRZOOHFGHHWHTJTZDFXPJABPZODXWSKVJNUQPFFCVVOOEDJLXPNDTSTYCHCTVPFRGYFNOBAQJWIRPFPEXLLFRYXJCAASLJJDSIRLKCOSHHSQRQHASOJYRMMXMCBVRFPEQGVPOAEKIGRARRSLTVUUBQWNWYBXUXPXZHMBYNPSOTYPOAAFYUXPPTKKXHZKWXAEANBXIWIXGHQUXLQQIKVOGPBTXNEECSNXNRAIMAXIPFCVMPKORQGWATVRDZLHDSTNMPZZJAKJKZJXFYCZFPSABRRLHLFMQKKENQXGFDKPDPHRRINPNDHRWCLXPKDRFZFRRRRRRUFNAMHSWDYCCIQZASPZWXHRYGPYJIIACRCMINSCQRXNRBHJLBXTZVXTIEUHBVXFTOCVSPGFSFPAWTUXKRIXPCNHAFPUYZNPDDTWYZNPDCCXWQVJDNPWSXPAOAXWOVMPCJAPWGWPLUDSAZDECCPXDQFUZJEAATWMVDRPJYYYRFRXPRFBJMABHYOHCWMAHDTIYYNOTXTOFFFUJYPSVRXFNFMPVAZJOUBFMQCBBWNEWERHLDUZFSFZOGDSYGGKMQHUTQUOBFXMISFUWBLVIXVAOVQIMDKPFRPFYTMENVWMMOCHKVLNXAPXTCWADKSINBDDMLMZDAUOMRJDVNUJHBFWGMMXTLEUBAVCHGEOCSBFLYIYPYUZAKXLDYCGDDGRCKCBBTAEBDBCCZGVTSEJHQDVDZZEOIDJPDXFGVLDAOLUVYULAJPMKZPRUZJISYLFRZQQFQWJEZMHCMKWOUBPLRAYDVTBCQCPRRYJRHHJHXHDABSBELBWKIOBOIFYIBNWCJTWQUFFUNFOAAFGZDDLDYKPZDPSFVGISJAAAHRLSNLDEHZHLBEBRXXBQMAWISREVRGVJLNWHMAJXZQKZEZKIWSOOUAUHOBBNIHIWQRWGXDYPODNYXBFOQYEDFGXLPWSRHHRBDQKGHSAPUBWCIYBNVEDCPGQJZGJRJQNFAQHRAFKZNRFEEHYYFWVDLQHSTHJFAESEMOZYTZYSBREEPRBNMUAJNLPWDTMMMNJLIUXZIJXJWYYFQLLXRRRPRHNTJPTZPNPTXPMRZBURHKAHKXMTQRBRKLFLNLTZKCSGWZRIZFWKWRBDDRSISNPWOLCCBRBZCZHJSLEZHZHLAOYMNNYUSOCSQMAWIAPFTAJGZCVBRLQEGQBIEIZJJLLHTLDVQUEOXVOFWGUXQOZFZJNKIEYMYSMVQVMICNLTIUMEPZZGHKSGGSBGQQFQPHOCRWNTDEDYFKWKRIMJWRKMDIAYNZPSHROFFGJEYXNFXLKJDPKYEMMFPSYYQRFBWTRNHVBSIWSTSIVSMHBDMNBRQPVOQBEHFWOCXUYPNPUXWGVGUPPBUPHQNIELGEUMWFTUAJTVIKDESTHGANNNIJUZZSTLLQLJKHJNZQNVMWPWRFXFZZXDWXLVEKNINXBCOHQWGXNJMKAPGQZXAOCHCXJNZYBHMTOBTNCVDVFMHKBLELGUPOQRTXKMWWOGSICQXQXLGHOFTTAGDTBHVJSSIEIIJQULIHQNZDHQQLZOCGRAWZFEPYQHQMUWPHEFEEUTBAQQTEQWTJRXEDQNHIZYZSJTRBORMSIAMMUGISXPVQHDEMELOUZYINBBTMDNDBCCZGGQGDCSCOWERURCXNOMAWEVRXKMBFEQWHVQJRMUZPOELMLLVLCJUATDIDBIEMCEIARXHNUMJISIGQLRMRFBHWEJYWNXCLQVTXVWQUIIWGFVHHAQERVLGGOCEAWYUJFVICWOLUOUVOMZCHYYMOSIIXZCHRSGXCLQBKZVPQVLXVLEZSKBWBUIJXOPOFKPBLQMSDXKVHWTZNUQSOIETMMRJRYPPZDAAPDEKILIQEGWCXMIOTNFLLPBMUMTWCHGQVTJMXMEOREAWJOYZHGIGKTMGHMWQLRXLFNODIDIOZJWMCVQEOXCKEZKENCAXMRYOCFWYEGUKTGEEILMAEPFPXCQXTVRLYNSXUMKZDHPNJZCBHVWVNXSJKJJTJAVLYYRUIDMJEAFTTUWQFJRUCYETRKGNXMFYZNJRPYTPDKGKYZZQQEPVBIRPYJFICHHQZEESKDSUJQEGSKBBQFBJEAVAAXFOPDIVZNLULVIMILKFIZNOQPFVFJGCVHZIACTTRTXQDVXSSACGOGVKWFHIVFQOKGIETPFSMGGHILMCSAVUCULLAPLTOKFKKHPYZNSFJXVEVFSWSVUPVKINTXMORJKWBNQMEZOLUOUOCYEQUYCJSGHXXLJRVHZQWTXRCCRCSVCMUIOMGFFNRRVKTGMKFQQNAAMSGBTIRCPVXWOPTRFRNOGYPGTPWHYILZFBCLYWAFSUFQYYQHETZTCLGOPKKSUFHAALUMJIIAIDCYYWCAIUMVIFVNEQXLXMELWHPWXWBCYVAVGXXJBJAAFHVIWRIHEHTIHRXEWTSCSQAVMWETBXPDVQRHHXINTXPWZWRWWWYOOQOEOKHMMEWMMCZAQAVXQVFKKJZNNFFVJFGFVDLPLCKUYDEDLFOJOYDELBDLNQEANKQWCGPVWJBMAMXBFIEVAEAOBGRCOVWVABXUZUFWWWVIZOPDIVZNLULVIMILKFXFYKCSSISJUGUUUYVUUKGKNIOTJJXACREELOVUSIDSIDRNVVHNBGBLJVNYIOGSDZRXLLHRYMIOXVAGCISPWGOWKIOBDKYZQERJNUNIECCDKBXVRFVXJRYRJZZPPFXEWESNBUROKESDJZVNIGRCKYYBJAKOQQCLQAVLBKLVBCNSDOZNFWGRJIXDFVYOOFTIECJRNHHYPPWAKXPDFBUKKLDVMDQMTFNNERYPKCRSXNLVPFYJELTEZLBXMIYLFZSJPZLVJMGRGEBAAHEHXKMCUNZPPCHJGLUFOYGPXNBJKZISMZCCUKLXYGMXLANUTINOCNRAWBVJRHSHEXPWYPTAUGXSORPRRJCTZJVBWEFTNMROPPPBYROJETDWWESJRPNLLDZKKIIZBDYNJJNIEIIATKUYYOMQINBIIMWPWUDOBHYHPAXDPWOMXCZVYJMPAUWKFNIXLCIQGBZNZFFZQGKQYAVWSHVPBRGVCCRUYYURRIJXEDPGUMHRSATYIIQULROJGCMPUXPXDHIHOABREVRIFQRFQZNCSGJRXDLGGCLAEABXVBCBIUILFRDUINXBCOHQWGXNVRKAAVTLJWRYTUITIXDBDFXWAEQKWMGLGQYUTSDRTUEQRUHWCLULBRXDWXOKWBPBYXTMNELGTHJLNVLPGNNOJUGGGLJDQOMBLANURRIOKKSAOTDCSHLORHHTIBLBGJVNZRPGFVQBRVUHGKMIINXHQFZAWMCOEEWXSLUQKLZQMWIZHPYMCMTPXNRIZVBSTSNIYBDFQOOKQAUWCLNYRZXPZOYERELMITNEOVEVFSHJYHNKWNJHDQSWQYRTFVLZLFUSAKHVSJJLRQQFESIYCAXJBLIDVMWBAMOPPKCXNFUKNKAGWKTMBJBIWYAOEETVKTZWEXOFPKGSYFXHJUKUORRFMZVSXMIYWCLGUWCFDTVJJWCPAGLVASFQWFLWSIJMNMHVJKULBVNXGKJEDTDSLEFTOITLBFTRLCDRBQFZYTZWMUACCSXSXNQGGNJBAYUWRVYQHHYYMKKGBTBOWNFQAGYKVRJLWHPZUZVTPEDEMFNFFUWUXUEEJJXNEWKCVLLATPKAYZISULAZJVSAQDAEWUAJXAUTOLEVFYJUDYEDETRZSXHBPTRTYEPCQQPDZMAPIFJLGKMPXHXOCDWNXYQGGWENIZFVJINJRJQTZEDNSJBYFBDUWHQOYESHQQGQTWMRSGHCCDRUWCIQCAGXGIWETOMCUEMEKBYBNFWJJAXCTFYMJYLIWIKNMIJTRZPOEQNAYPCLVXNPSEKNUEFPVXOOYCBUJQWQPGWPVBRJRZIXCUQGVMLTPYSKHCGVVIFQANUUCPHPIUMCCJFMWUASGLRMPGUVUPOPLPTFOPMJFSNIBTNCUZWTSVKNVGYSBNKKMQIZJEAAFFGZMNVDJMPCIPUOKZJIODNROGHVMXPQMUUFTXMSGSMNLWOJHDOVNGXADRSIIFBLBBXZLDFKNFKQAFBHEWKXRWYJOHZTLOLCRPFJNCSEGLVKQLAXHZZRHKHKYARJGSTLRNUXKCIMPGRHKULYAXJPVALDDBAZAKLZBKOBHMVHAJYHTBWSUEJOKIEYMSPQMBPJVDYXFQYQXAGLKUZCAWXQISMFEYNSCDRUKXLQGUDRABNVCQHYKLDZUPKGPYMVQJHXSHXSGCSNOHZHIKRCEJXEEVYVCKZDCTBISFMRAAVNOGYTBXYPDTPFYDNAFVQDCWJURZMNDTFFXOLAGAJSNFCFYTCQMQQHMMPXILAOKSEDYFEGHCVCDOJTXLJSCRHZNBKDFYGCDCUESTZXNGIHCZVJPZEGWPILAPBGRRCFAMORCWYMYVQVNLYIOHWKWACDGMUZZKYUAJWLENMFFQXKMKDWRJETBREUHJVDZSVXTELGQDJUDLSRMJVDKYPGSTLHVIUCEWMOOWCFTQTUPOGTEPXEFEJKGDIDOFFRJRIINPDQEZQPMPBQPZVJKFGFAXDAZJZXHCEDOXJSCRDLHAQFBBFAWSNNXJCQBCLHKYYQOHASOSDLWEMZTYMHNYEWRIKJZSCERBSSSWYOBREGSAWPSUQWMACPVIKWOZJPHTEASHNZHXXDSTYTJLVVESQSJJVRBDFVVVXBGHDSGAMWGMXYEBAKAYIDGLIXAOAXDVAGQVTVHKYUOVTNCHVCYHWQQKRMAFPSYKSOOBAQTBVCZZQWSSAIBIBAQSGLVMCOUWMHBQUGSTVQFUQQUPLHCMKQXAGLKUZJAXJZDZFQSVBAMOKTHXPDPXWBWGEXYMBBNWBLGWMKCZAZUIWYWQXIFXTHWSTHTTZASGPGQFDIBEMDRNTPLVTKMGRJYCXVKFZXUQWARUXFGZPGGPRBOIDQQHLNYBEVFTTFPBRPSAQQVQQYAEFTUXPMHBPZGWZGHGSQOXKESOCXEORJTXAGKXTXWPERVMYKTFETYRDTNKQKCOGNNYCOELVAWRZWRWZLZXTIZBNTWDVAQEJPKWWQZVRBHFLZHZGJPUTDICJGSRRVZMUBRIRJFIJXLINSTJTBXQTYIZJNKUDSLZZHGVCSKUBVSRHROPFTGAEULLGRPAGATVIXDWGTAGOXFINJIOUOCIRGALMCCCOWYUFNJEJFWCQPHTPKMNTNUPKUCDVARNFIJPKSQRKBHRZYYOKODIXKYWWOVZWDVNRDWOYNELGKKBZPFUTUFRYVHHNRNHHYPPKPIMZDOOUHLXNFIISIOGQFEUXLNPUUOKISJFLEAPZEWBZONREUCJOWGYNVLDSTXNEIFHVMAQYLDSOGZPAZNQVFCBBRNRGDZDADJQVMZGGRQLZLXUHZRAWEKRWMMVRQVYKODDOUUVOOHWFUNBRUIXNPSESZBSGBUISPFBURGLHRAPXPDDSIIOUOFAUJEIXBJNWEABULZAQBRBKUOOTCAMRHLBGYAWMEEJFKIZZFUOCCYOGSOJLMSRKKDGUIZDUVUHYBPQZJDAGKNEPTFORYCWKMCOYQQXAQQWQEOLLMBDQVGNNTIUOFVERZVNCHCRKKNIBUZNNBFDWMVPZUXOCDRRHSXXANWXKRCFUSCQQBREUNUJSQRXRQCSMUANBOHWCRPGUQAAIEYQILHKKUIHTHUYGWSOBGQPFUYBXHIMNXFQSWYAAXWEIYBYXYOFORYUQKYWXSVKJMEYPLVVXEDEUYPPWCGZLBTCVOJQWIEDJOPZSPJHNECNKOFEMHPYZJPUBCUWIQMDALSKTTTEXNPFRTDCSEEFLMAZFBEMMDZQSRHALFHXTJTFHAKVQCYFSOTZWRYGGQYZTGKEVAFVWNQFRFRGWXEXVREWFFFSLVSAGKSHNYZTHFXCCCVMJOLTPOOEAEARWMIFHDIZCCQALJMRBBJNDMPPFQSTDKGBUZIHHXTXLVGEAWTOJBYIKAAJUQTSIBMNTJMBNHSDMHNMNCOCQBTWJMVKLAOIGOOZIKYKHZIFPDDOEMKYUHAJJTBMYCOWTMIBUISCWMQUDLWTLVVSWBBBULINUBUCSLOARFXFIFSPLTESCDCSVVWIFEDIILFBEBUHSJDAZCRISJPJBNFIKHPGQSQJDQSKHKBOOFDENJMTRCLCZDQDFOUBERDHRFFQGKJRNYHPWCQVYYQMVWQWWGJZPRBFIMYETPWOGBDDFJALLSCPSPLFBQGDCUTATZKTZOAOCNFNRHHNVBCSLUKTFEJUMYUPRSYLZWHKWOMUOPWVOENXYTBSQUTWGGGGGZHDDIWITZMRRHKDVZZONZBJGBYVKQRQIWFNBCCCPZLNBMQNONBDQKIPTZEKKHMRAEHNNENREJLMGIVIYVVQPPKBWVDOWJPYAMIZIXCWKGMVBRUUGVLMVWCGALRLJDUOFTPZBAWJBLLIEIFJVXHHZJILJMMUTIPBDISUYBNCGWANMKAELYUAPUQWVOYPJUJZLZAVSGQFRHZCWNKDWKKGPGXAYODUETYLOENVBTCCHPEOLDXBEGUWPPRANVOAXPYYACSEOZAKQRCAWAUDPSCQNEAFJPIJNNXBXMGUQJJNXIAPPPWRRRHLCCCGLRMNEJHUXJXUTWOVBDDWECAYWEUTJVYZIZJEAHOPXJBRRCDAPBFGCMKUCPVEGSOVNJXXDOSUGTTTTTTXOKQOMONNSBUNIPVHDUSKIHMUOJUOQNNTGTRCSCYIKMYDDKMWXYWKGOFFUJFNIEZEETOJQGXAHGQJTNUKDFRJHXNACEJZVSUQVXAFLGXXYEYGAVQETPWKZZZIZKFBPWPTGWHWEVPXBOSPHZRPDZBJLTVDMAKZLBMFPPOBAQTQTJZKSIIYUEFEUGLWOAWRTUARIVVEDKAJUUNHDJXTMOFBHNXBBFNMCXZHZHYLCCCRPINFMVZQKPQEETOVAMAHVFSGYTMAGQGAJDIXNOCEIOWRVCZBLWFWGRGZCWWWIHDGHVSLOUBUKJELQHJYAEMWODRRPGLGWWJYAZLPGDCLIGGNXCOTFROFFHSGHOBXCIFASQHZTTRISWWOKTVPYXYZYHRSXIEQUVNZRIWCMDNRRIZZJNKFVGHGYRTPOQRMESQLREOKMIORRQUNMXDWCELIYVPMWHDGHVIDYUQQWNWYMUYLPMEHJPKVNOUOGTZFGSYZNTLHLYAOXCWSSMKPOIUEDQHWXLWKBMTJAVRBBIKUFDNPFNZMAZEDDTPTBPXBKSQEFACOGWWBMMFZVGHLLFCKHRWNAWXWROHYMNPOCKWIUJSGKFGVOHIJJHDRNZRMUANADSLLBSGHPXXZPZBXEPEONVYIGBXPNZJDBUNILTATMWCPBWTIGLLLLLLOSCGKWDLOCHWHQLLMEFNAGPRDZQQCRVUQDIWILKVEJWSOKNZHIUKGNGEKEPDKAWTBJORIINALHJWBHCSTPMRMXOOHWLFRNKIJQUREIKMCGCIEUIOSNDXTPUETJCKAMCCSYLBIQMASJZVTFLAGOXFIIXDMEPHEMIGUHHRISIGIOOSAYBYGIDIGKCYKINUPKMOHZAAOBBODBGMUIYHRHVDWUTLQWASZJOSJONIDGMRISMSTPMRMXOOONARCONHKAQCXHFLDMCGSMGECNZGBNRAFNVBFGFRLQDNASKKGEHNJLQAMULVZRXSSUYOOHPVCBOFUVJSCAOSEGTEQAIJGMRZKHVMEOMZIIALTNRDZAZEARFSNTRSXUCZMGUMINYHNLDKRYQBVLOAGGAOUXFMARIUVNJAGBESQQIQYEXPJYYKHPIZQAQEUPWIAMFWPXPYNGSKQXLHNWUZUJXYIKXRWYHFHXYPYAZBGOHWIKTUIFMDDDZXAGCEYDFLQRSSUUHDFSAGJSHZUDYUGYGEIHLYFHOJNNWCLRBQXTQEIBCFWGHRLRSOLQLWNNNMZQFGUVUMNRPEPLCDFBGAJHYYFTHZPNGJVPPPTKKESQSNJTRPMGTRZXEMHDAUJCVWKKZUBGFKBLRGTRNODMIJWMMWKKVLEKEPUXJBTNIAJVDPPPGYZFZREKFXRGGSPXQHYIYMCXJKCZREIJXHWJMPMWDYESYMVBMHTPWJFKQNIARBCMGMNJGLGRIIIGPAHMCCAGOGQQGGSWFONBTVZMXIVUKBERJTGWAMSORGGBNGEEWLTXOUVOFPQIYYOYMRWXJCLRBSIJXFVVMSCPIUPNBBQJHTJCSSCENBWRDWCVWQSQEJOPBUDJTKAWFOKDBNXLXBSGHVLLLLMTDOMPUEQQLBQMUPLGLLTKOLSPGKRKRNPFTCQZAMURBGXKGQUPOMUVJEUDIFXITPDYBTWVPZNXMYOBPIIXZQIZHWGNZZRDUKCSVIUKPDAQWNOJYQVLZPKQRHYUFACFXXQYUXAYORVSVCKBRHNHIWYRWGQHQFGUUGCAFPQBLZDVIIABPPAORUYXQFXONNCCSIVRFTKJOUPVJXZXNRVTKGHQHRMIAAZPVQFYUPTTSIXBEGVKKVTUTFXMEAFKBVLEUQMGZMAJFYSNWZJEDLDUURFKPQCVEKULBJKZWZBSVLKBRNDGTNNFXORLIPKFHVRJTHGIWVFRPRPNJMUUCHBPGKUJNLJJIUJPJBOUNCRHPVUEDTFFFKFVPVRTAPNUQJAHYEGIYUQRFVQWXNTGTJIWSEOPBLBTQDMGKNTTONHUMSRWRMOCMLFSQQXPJAQCSELMLYYDXITCXDCDSQQUTYEZDLPJQJQEZTQFVTASIIYNCYDHZHWLQTTOQABSYEIRXYVYTOHSCCKHPQZCZJQLRFLZINDBOYWYZFOQCYXXEHXBOVAAIZVBRFCSYOGDZQLZBBKDMXEAJCLPGBBRQWBPVITNEGVOTFWIOSZAEHJXMKBWMIEQDTXVPQVJQMFEYLATCNMHEXOYZJDJKGDIDOFFFDCOMJITPIZYSFELGPTLDUJZQJYMLVIUFNFMPVAZJOFDXABNMMOHQAENGGPOGEDVURCCZOYXFOZSTZPHZICSJSKAXRHLBFDRXTPPOSLJKWNNJEOMFGURQLRCCVPLWXBUXXWEAGJNANBDDXHWWCSLTMRBCKWWLPGPRFNOEEFQUXECCIKYJPPZNNYOSCVVFETYZXGNCGKACUFXPIIVKDNGTFVVBQKRMHPPTKEGOCFPEUAMCSTIDXDSEUWYDQAVRHCEHIWRHQVSKVGCQVQVMIWDQNMUNXBEKGUBPHKQLDEGTSOYNMUOJGDODCXGWWZMCSMZUPHSAYZSQSOLXCSBBZUQOGLVKLDASBWYGOKWFJBSBAIBNBAVSEMOZYTZYSBHVJAGKESAQQANCWYEQMXBTROICKDWTXMXMGJNLXQRVTRRQCJKJWWBVGRAVBABQLRTVNIMQNEOFGAUNJEVSHBBEKWEUUMOLZAILSHQUXHNQZOGBYCCZLBFMSSIMDDUQAKOYYFXKQXCUVUVNRTVRSGUNYSENVDZYYOKOCRPLJEOEVVMISCGQQXOJPQGXTESSSWYOOBLUKKWFKUPFVEFDWKODFHXDYQAJOWQLCMUFHPJACDKOLZBMKSLXERBRUADDNHTABAHPSKGOSSSXSHAOYMMXNVAXBVCYGGQVYKCUFQBCQTJPQCCQDWVXVDQOKMGPSFRZFJLPRKSWMSZCHXPJFTNRAVOSSZNZXBSVMZOAKBRBMOYHCQHDQSSRLLKHRUJBCMSIISIZIEGGEVLUGWZROBFWBNJOIWMPNDNWILBIBJBLANXNQLRILDZLDYDLEJTTIRBTSEYDRSFTSMKGFCCIVIDGHTODRFQWKKAPVZQCQCTQCYLWODWGZMCSELMLZNLVETMFDHUNNTCSHEJOLTPOOEAETYNAOIGPHLMAGTHGEVQGGFVVKLJXFZTIORAZUJCRXTVCCTCKTOJBYINTOQQJQJYGYIIYYOOQIBLEEEPDMIBDZOEWLMQUYLLRDGGWRWBESIADBRNCLHNUQSGQVZPGTATUYSHFVXXDZDGKMLPIQSWKIDBERNPBBGRQNFZLIUYGCNEETRXKHGDRJBNEXQNQRDJLNDDQAJZZLUZJEUKSGSGIACXDYVYMHPWZMMOOODWHXOXTVAZNYCCCCCCGEFXISYQCNJBHVFEOBOZFWYKCAICDKAYIGXBPDUATLKNDEKOFVOSCESUMBFOHJJOCEEYUTNNZWHCORHHUENDDPYDNIYOCFCGLONFHFAZPSGEVPNSIOBXTVWKAALMWJWMQECCUUISUHBXWFALUJJUGUASYHBWRITOADTTGYDNCARKDADEQWYSJKXPZGATRFLMLZNPVVGWPKUDSQYEUQVDKORXLZQWAEZUZZERJSUIQGNWKKOPSPTOKKWUICTPPWKQAMPGGBGMOCSRTFNYENJITECAOYNZPQGACIKRJGAGANSNCVXTZEDZHNFTFXTTACFDYJPQPFGVVGOQJKUACTTAPUCWRPJILBUIDFGLWSEWMMOYGMVVYJHIDZCDRYYTCGPRUEYPPFIPHXKQGKRCRHJIMDQAQHHOWFAZUTJKVRISWLBXNFIEWDHYDMSTUTVWKBXDEFUTZOUYBSIEDXZJUPBXERNSYVQGSNORYUYMNPKATVUUMQNGLCQEVNGXASZPIIYBUUUVTTPKCKXFGBZMRLJHYTJJIMFEVPHHOBEVOZXFMITJYDYOWKPVQEYUYCODGDRBQCSMTMUOEBRVHBSTHCGNRMCGVZXMFRULPQOYSQJCQFCEABCMRQWRBCMXVYDNDSTSILYYTJYUCXTOTTESSOEWIEZBCINJPFYYJVGCCVXVDEWTFUVLBUPIIYVDDXPPPGBHMRYRQYTJBDGQWGIMAOQIHCZLTQAFWJFWSULBDHPFNONRKQNDLRJTRLAKSWWAPMIQNGPZVAFJBPNDCUTQQYYTQJOQZZUCJCBGEQABNYGDNSJWSXSXZDHPVJONPVYWMIDRDPMZRJSOWGKANDNJWMPDSIKNZFOOJASPSQSYDAYNSIIGOEYESOPHQCZAZMMRLWHQLRQRGEMFKULJPEQXJYPRFZBLLNCGPUGMRXCFELBLGXBYZYYESSEXYVVRJLNRTVCNWUUKVGVEZZOJYOSUJIZXEZDFYQZLIJIZOFBEHTCQEEUXIDPSIIVFOEEQZEOJZPYGBOGOKRADAEWXLJEDETUYKYSQMEYKTNWYXOOANUACMAGHKUJWFFUWIALVBTFQMEWYIWCEUUFGDSEIJFPNDKZPGVYGVRLTCTTQIOVTCOLMHDGHVEACTNHLYQPQWCZLLBSOJARHGYQKIIKHNTYIACRFUGNRBVTFCDCVRJCKMOUJLXPDUIOFJLZCKSWEIYHKAALMJYKOPLVTJUOOOCJVWULRSMKWMFCGLVLZHDVKXXKDHNJRZBFROPOZQWNLAEPKWZPPGFUTUNBLUKKWFKUPFVDFPTTSIQOLHZQAOOAGIXWSPXOYHMRNNHEPDCSVCNCBXYQHHIQTSSDDUTKFNRPKFFNFTGLRMOZYHUNZLTPVKBBQFBJEAVAAXFOPDIVZNLULVIMILKFBGXPYZGZXDDOYODHKMQRKWKLWMBXKPBZEURUCAMBBYPLRDNMCOOKPXRMXRHWSOWGSULHNSCWRAENYDFWSFJYOHHCVOTHHLXEMVDZAZZBFLSCKMEFLFXKQVXGJISKHYYXNXWJACUOBBQHGRFSISHLOFQBJEOIXKMAMSSDMBPDPEPYAXSDQWCPPFFMSAYZRXESOUDBGWMAJXGHARXHIHCROUEFMMHUFIXJIXCTRNBWTGKHZJHRISLOCEEDWYYACYXZAOFFPJSXIEVRDHOSYDJLZPDYDLFACFSCMKKENLANPNROKIAYWYOHVMYEXLJZNDQIMKBSBDWBLWQMVFUZYWOYYOOCUSPOLIDHHTVNCXPJVBJSEWNJPBLKAMMFVJWAQLQAJGBXQNNJLJJBULRBAFVHFVOJCULUNGBCSUSCATBEERXNPBMZJUZWAUNXUFDELONSFXGIWETWD";
        static string keywordText = "";
        static string randomKeyword = "";
        static string permutationKeyword = "";

        static void Main(string[] args) {
            Console.WriteLine("Homework Section 1");
            HomeworkSection1();

            Console.WriteLine("\r\nHomework Section 2");
            HomeworkSection2();

            Console.WriteLine("\r\nHomework Section 3");
            HomeworkSection3();

            Console.ReadKey();
        }

        static bool HomeworkSection1() {
            // Start finding key with only known cipher text attack
            bool successfull = DecryptWithKnownCipherText();

            // If known cipher text attack has not been successfull, try known plain text and cipher text attack.
            if (!successfull) {
                successfull = DecryptWithKnownPlainAndCipherText();
            }

            if (successfull) {
                // Decode the cipher text with the found keyword to check whether the found keyword is correct or not.
                Vigenere vigenere = new Vigenere();
                string decodedText = vigenere.Decode(cipherText, keywordText);

                if (decodedText == plainText)
                    Console.WriteLine("Cipher text decrypted successfully!");
            }

            return successfull;
        }

        static void HomeworkSection2() {
            // Generate random key with the same length as the keyword.
            randomKeyword = Utilities.GenerateRandomKey(keywordText.Length);
            Console.WriteLine($"Selected Random Key: {randomKeyword}");

            // Encrypt cipher text with the random key.
            Vigenere vigenere = new Vigenere();
            cipherText = vigenere.Encode(cipherText, randomKeyword);
            
            // Apply same crypto analysis methods in section 1.
            HomeworkSection1();
        }

        static void HomeworkSection3() {
            // Generate random key to apply permutation cipher. The key size is kept relatively small for crypto analysis.
            permutationKeyword = Utilities.GenerateRandomKey(6);

            // Encrypt the cypertext by using permutation cipher with random permutation key.
            Permutation permutation = new Permutation();
            cipherText = permutation.Encode(cipherText, permutationKeyword);

            // Apply same crypto analysis methods in section 1.
            bool successfull = HomeworkSection1();

            // If crypto analysis has failed, try decoding the permutation cipher first, then try steps defined in Section1.
            if (!successfull) {
                DecryptPermutationCypher();
            }
        }

        static bool DecryptWithKnownCipherText() {
            Console.WriteLine("Starting crypto analysis by using only known cipher text.");

            // Convert ciphertext to numbers.
            IEnumerable<int> valuesOfCipherText = Utilities.GetValueArray(cipherText);

            // Apply Index of Coincidence analysis to find out the block size.
            int blockSize = VigenereAnalyser.FindBlockSizeWithCoincidence(cipherText);

            // If block size is -1, return false to signify the known cipher text analysis has failed. 
            if (blockSize == -1) {
                Console.WriteLine("Crypto analysis by using only known cipher text failed to obtain block size.");
                return false;
            } 

            // Divide cipher texts according to the found block size.
            IEnumerable<string> dividedCipherTexts = VigenereAnalyser.DivideCipherText(cipherText, blockSize);

            // For each divided cipher text, apply frequency analysis to find out the shift amount. Store shift amounts for each divided cipher text.
            int[] shiftAmounts = new int[blockSize];
            for (int i = 0; i < blockSize; i++) {
                int shiftAmount = FrequencyAnalyser.FindShiftAmount(dividedCipherTexts.ElementAt(i));
                // If shift amount is -1, return false to signify the known cipher text analysis has failed. 
                if (shiftAmount == -1) {
                    Console.WriteLine("Crypto analysis by using only known cipher text failed to obtain shift amount.");
                    return false;
                }

                shiftAmounts[i] = shiftAmount;
            }

            // Obtain keyword string from shift values.
            keywordText = Utilities.GetString(shiftAmounts);
            Console.WriteLine($"Cipher key: {keywordText}");

            return true;
        }

        static bool DecryptWithKnownPlainAndCipherText() {
            Console.WriteLine("Starting crypto analysis by using known plain and cipher text.");

            // Convert plain text and cipher text to numbers.
            IEnumerable<int> valuesOfPlainText = Utilities.GetValueArray(plainText);
            IEnumerable<int> valuesOfCipherText = Utilities.GetValueArray(cipherText);

            // Store all the shift values
            int[] values = new int[plainText.Length];
            for (int i = 0; i < plainText.Length; i++) {
                // Calculate each shift value between plain text and cipher text according to Vigenere cipher.
                values[i] = ((valuesOfCipherText.ElementAt(i) + 26) - valuesOfPlainText.ElementAt(i)) % 26;
            }

            // Create the long keyword text from obtained shift values.
            string longKeyword = Utilities.GetString(values);

            // Try to figure out the shortest key possible, a.k.a find out the repeating text in the long keyword text.
            int blockSize = 1;
            while (blockSize++ <= Constants.MAX_BLOCK_SIZE) {
                List<string> dividedKeyword = VigenereAnalyser.DivideCipherText(longKeyword, blockSize);

                // If a divided keywords all characters are the same, break out of the loop.
                bool allSame = dividedKeyword.TrueForAll(k => k.Distinct().Count() == 1);
                if (allSame)
                    break;
            }

            if (blockSize >= Constants.MAX_BLOCK_SIZE) {
                // Found keyword's size is equal to the size of the plain text, obtained keyword cannot be correct.
                Console.WriteLine("Found cipher key's length is equal to the cipher text's length. Cipher key couldn't be found!");
                return false;
            } else {
                // Get the actual keyword.
                keywordText = longKeyword.Substring(0, blockSize);
                Console.WriteLine($"Cipher key: {keywordText}");

                return true;
            }
        }

        static bool DecryptPermutationCypher() {
            // Create a Permutation class for encoding and decoding texts.
            Permutation permutationCipher = new Permutation();

            // Store original cipher text.
            string originalCipherText = cipherText;

            // Start trying permutations from length 2.
            int currentPermutationLength = 2;
            while (currentPermutationLength <= Constants.MAX_PERMUTATION_LENGTH) {
                // Create a list containing numbers to permutate, starting from 0 to currentPermutationLength.
                int[] list = new int[currentPermutationLength];
                for (int i = 0; i < currentPermutationLength; i++) {
                    list[i] = i;
                }

                // Get all permutations of the list.
                IEnumerable<IEnumerable<int>> permutations = GetPermutations(list, currentPermutationLength);

                // Decode cipher text with each possible permutations. Apply crypto analysis defined in Section1 to decoded cipher text.
                foreach (IEnumerable<int> permutation in permutations) {
                    cipherText = permutationCipher.Decode(originalCipherText, permutation);

                    // Apply crypto analysis for obtained decoded cipher.
                    bool successfull = HomeworkSection1();

                    // If crypto analysis has been successfull, current permutation is the correct key for the permutation cipher.
                    if (successfull) {
                        Console.WriteLine($"Permutation cipher has been decrypted successfully. Permutation Cipher Key: {GetPermutationString(permutation)}");
                        return true;
                    }
                }

                currentPermutationLength++;
            }

            return false;
        }
        
        // Gives all permutations of the list with requested length. Source: https://stackoverflow.com/a/10629938/4594860
        static IEnumerable<IEnumerable<T>> GetPermutations<T>(IEnumerable<T> list, int length) {
            if (length == 1) return list.Select(t => new T[] { t });
            return GetPermutations(list, length - 1).SelectMany(t => list.Where(o => !t.Contains(o)), (t1, t2) => t1.Concat(new T[] { t2 }));
        }

        static string GetPermutationString(IEnumerable<int> permutation) {
            StringBuilder builder = new StringBuilder();
            int permutationLength = permutation.Count();
            for (int i = 0; i < permutationLength; i++) {
                builder.Append($"{i+1} -> {permutation.ElementAt(i) + 1}");
                if (i != permutationLength - 1)
                    builder.Append(", ");
            }

            return builder.ToString();
        }
    }
}
